
name: Triage and Remediation

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:  

jobs:
  triageAndRemediation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: AppSecAI
        uses: AppSecureAI/submit-run-action@main
        with:
          file: vuln/output_sarif_100.sarif
