
name: Triage and Remediation

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:  

jobs:
  triageAndRemediation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Checkout submit-run-action
        uses: actions/checkout@v4
        with:
          repository: AppSecureAI/submit-run-action
          token: ${{ secrets.ACTION_PAT }}
          path: .github/actions/submit-run-action
          ref: main
          
      - name: AppSecAI
        uses: AppSecureAI/submit-run-action@main
        with:
          file: vuln/output_sarif_100.sarif
